"""indexes_uniques

Revision ID: 2161b33631f0
Revises: cf017868b888
Create Date: 2025-11-07 11:38:32.970600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2161b33631f0'
down_revision: Union[str, None] = 'cf017868b888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    op.create_unique_constraint('uq_assets_symbol', 'assets', ['symbol'])
    op.drop_index(op.f('ix_prices_date'), table_name='prices')
    op.create_index('ix_prices_asset_date', 'prices', ['asset_id', 'date'], unique=False)
    op.create_unique_constraint('uq_prices_asset_date', 'prices', ['asset_id', 'date'])
    op.drop_index(op.f('ix_signals_date'), table_name='signals')
    op.create_index('ix_signals_asset_date_kind', 'signals', ['asset_id', 'date', 'kind'], unique=False)
    op.create_unique_constraint('uq_signals_asset_date_kind', 'signals', ['asset_id', 'date', 'kind'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_signals_asset_date_kind', 'signals', type_='unique')
    op.drop_index('ix_signals_asset_date_kind', table_name='signals')
    op.create_index(op.f('ix_signals_date'), 'signals', ['date'], unique=False)
    op.drop_constraint('uq_prices_asset_date', 'prices', type_='unique')
    op.drop_index('ix_prices_asset_date', table_name='prices')
    op.create_index(op.f('ix_prices_date'), 'prices', ['date'], unique=False)
    op.drop_constraint('uq_assets_symbol', 'assets', type_='unique')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=True)
    # ### end Alembic commands ###

